### ISSUE TITLE
Small sized wings could give negative module mass  

### ISSUE THREAD

**Issue by whale2** [Crzyrndm/ProceduralWings#5]
Hi.
I've found this issue and tracked this down to GetModuleMass() yielding negative mass in some circumstances. So, if procedural wing is reduced comparing to its prefab size AND FAR mass-strength modifier is used to reduce part mass, the wing freezes in the air. 
Expected behavior:

https://youtu.be/ghqe-4UlOKI

Behavior when mass-strength modifier is applied (http://i.imgur.com/2l4RgIX.png):

https://youtu.be/ARYLeU3A7I8

I didn't track it deeper, but feel that negative mass is not very good thing, so this fixes it for me:

```
--- a/Source/WingManipulator.cs
+++ b/Source/WingManipulator.cs
@@ -602,7 +602,8 @@ public ModifierChangeWhen GetModuleSizeChangeWhen()
 
         public float GetModuleMass(float defaultMass, ModifierStagingSituation sit)
         {
-            return (float)wingMass - defaultMass;
+            float mass = (float)wingMass - defaultMass;
+            return mass <= 0 ? 0.01f : mass;
         }
 
         public ModifierChangeWhen GetModuleMassChangeWhen()
```

**Comment by Crzyrndm** [comment]
Latest commit should fix (tl;dr FAR already determines wing mass and these need to stay out)

**Comment by whale2** [comment]
I was not sure if zero mass is ok, but tested your latest commit just in case and issue has gone. Thanks. Closing this.
